#!/bin/bash

#  ANTS pkg postinstall script
#
#  Load ants launch daemons
#  Create symlinks to Apple PyObjC frameworks in ANTS
#
#
#  Created by Jacob F. Grant and Balz Aschwanden
#
#  Created: 01/03/18
#  Updated: 09/12/19
#

# load and launch daemons
launchctl load -w /Library/LaunchDaemons/ch.unibas.its.cs.ants.plist
launchctl load -w /Library/LaunchDaemons/ch.unibas.its.cs.ants.run-now.plist

# Change ansible-pull exe location
sed -i '' 's|ansible_pull_exe =.*|ansible_pull_exe = /Library/ANTS-Framework/Python.framework/Versions/Current/bin/ansible-pull|g' /etc/ants/ants.cfg
