#!/bin/zsh

#  ANTS pkg postinstall script for relocatable python
#
#  Load ants launch daemons
#
#
#  Created by Tim Königl
#
#  Created: 12/02/19
#  Updated: 12/05/19

# load and launch daemons
launchctl load -w /Library/LaunchDaemons/ch.unibas.its.cs.ants.plist
launchctl load -w /Library/LaunchDaemons/ch.unibas.its.cs.ants.run-now.plist
