#!/bin/bash

#  ANTS pkg postinstall script
#
#  Load ants launch daemons
#  Create symlinks to Apple PyObjC frameworks in ANTS
#
#
#  Created by Jacob F. Grant and Balz Aschwanden
#
#  Created: 01/03/18
#  Updated: 09/12/19
#

# load and launch daemons
launchctl load -w /Library/LaunchDaemons/ch.unibas.its.cs.ants.plist
launchctl load -w /Library/LaunchDaemons/ch.unibas.its.cs.ants.run-now.plist

# Symlink objc library
libraries=(
    objc
    Foundation
    CoreFoundation
)

for lib in "${libraries[@]}";do
    if [ ! -e "/Library/ANTS-Framework/lib/python2.7/site-packages/$lib" ];then
        ln -s "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/$lib" "/Library/ANTS-Framework/lib/python2.7/site-packages/$lib"
    fi
done
