#!/bin/bash
# Link ants executable to default path
ants_exe="/usr/local/bin/ants"
if [[ ! -e "$ants_exe" ]];then
    echo "Linking ants executable to $ants_exe"
    /bin/ln -s /Library/ANTS-Framework/bin/ants /usr/local/bin/ants
fi
