#!/bin/zsh

# unload ants launch daemons
launchctl unload -w /Library/LaunchDaemons/ch.unibas.its.cs.ants.plist
launchctl unload -w /Library/LaunchDaemons/ch.unibas.its.cs.ants.run-now.plist

# Check if an old version of ANTS (< 2) is installed. If so, remove it before installing the new one.
old_ants_bin="/Library/ANTS-Framework/bin"
old_ants_lib="/Library/ANTS-Framework/lib"
old_ants_include="/Library/ANTS-Framework/include"
old_ants="/Library/ANTS-Framework"

if [[ -d "$old_ants_bin" || -d "$old_ants_lib" || -d "$old_ants_include" ]]; then
    echo "Legacy installation of the ANTS-Framework found. Removing $old_ants."
    rm -rf "$old_ants"
fi

exit 0
