#!/usr/bin/env python

"""inventory_default
===================


Default inventory script.

This is a dummy inventory script to bootstrap ants.
It will return localhost and fqdn as members of
the ants-common group.

These values can be used to assign roles in local.yml but
using a dynamic inventory script like inventory_ad.py
is the prefered way of running ants.
"""
from __future__ import print_function

__author__ = "Balz Aschwanden"
__email__ = "balz.aschwanden@unibas.ch"
__copyright__ = "Copyright 2017, University of Basel"

__credits__ = ["Balz Aschwanden"]
__license__ = "GPL"


from antslib.inventory import helper


def main():
    """Print default inventory in JSON."""
    output = dict()
    fqdn = helper.get_hostname()
    output["ants-common"] = [fqdn]
    print(helper.format_output(output))


if __name__ == "__main__":
    main()
